services:
  ch_server:
    image: clickhouse/clickhouse-server
    ports:
      - "${CLICKHOUSE_NATIVE_PORT}:9000"
      - "${CLICKHOUSE_HTTP_PORT}:8123"
    volumes:
      - db:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

volumes:
  db: